debug: false
log.recipes.enable: false
data.backup.frequency.sec: -1
locale: en

yearmarked-show-join-message: true
yearmarked-show-holograms-on-day-change: true

yearmarked-worlds: 
  - world


#MONSOONDAY
yearmarked-monsoonday: Monsoonday
yearmarked-monsoonday-rain: true
yearmarked-monsoonday-allow-rain-toggle-with-thordfish: true
yearmarked-monsoonday-rain-toggle-on-with-thordfish-cost: 0
yearmarked-monsoonday-rain-toggle-off-with-thordfish-cost: 0


#EARTHDAY
yearmarked-earthday: Earthday
yearmarked-earthday-bonus-crops: true
yearmarked-earthday-bonus-crops-range-high: 3
yearmarked-earthday-bonus-crops-range-low: 1

yearmarked-earthday-pot-pie-buff-duration-sec: 20
yearmarked-earthday-pot-pie-buff-magnitude: 5
yearmarked-earthday-pot-pie-affect-entity-arrows-duration-sec: 60
yearmarked-earthday-allow-entity-arrows: true
yearmarked-earthday-entity-arrows-costs: 
  - COW=1
  - HORSE=1
  - DONKEY=2
  - LLAMA=15
  - PIG=1
  - SHEEP=1
  - CHICKEN=1
  - RABBIT=1
  - WOLF=10
  - SQUID=1
  - MULE=5
  - BAT=5
  - SPIDER=5
  - ZOMBIE=5
  - ZOMBIE_HORSE=5
  - ZOMBIE_VILLAGER=5
  - PIG_ZOMBIE=5
  - MUSHROOM_COW=5
  - SKELETON=10
  - SLIME=10
  - CREEPER=10
  - POLAR_BEAR=15
  - SKELETON_HORSE=15
  - CAVE_SPIDER=15
  - OCELOT=15
  - WITCH=15
  - SNOWMAN=15
  - SILVERFISH=20
  - IRON_GOLEM=40
  - VILLIAGER=60

#WORTTAG
yearmarked-wortag: Wortag
yearmarked-wortag-bonus-crops: true
yearmarked-wortag-bonus-crops-range-high: 3
yearmarked-wortag-bonus-crops-range-low: 1
yearmarked-wortag-teleportal-cration-cost: 2


#DONNERSTAG
yearmarked-donnerstag: Donnerstag
yearmarked-donnerstag-lightning: true
yearmarked-donnerstag-allow-lightning-toggle-with-thordfish: true
yearmarked-donnerstag-lightning-toggle-on-with-thordfish-cost: 0
yearmarked-donnerstag-lightning-toggle-off-with-thordfish-cost: 1
yearmarked-donnerstag-allow-super-creeper-spawn-with-fish-sword: true
yearmarked-donnerstag-super-creeper-spawn-with-fish-sword-percent-chance: 100
yearmarked-donnerstag-super-creeper-drops-diamond-percent-chance: 5
yearmarked-donnerstag-super-creeper-drops-emerald-percent-chance: 10
yearmarked-donnerstag-super-creeper-drops-thordfish-percent-chance: 15
yearmarked-donnerstag-super-creeper-op-luck: true
yearmarked-donnerstag-lightning-inhibitor-range: 25
yearmarked-donnerstag-lightning-inhibitor-personal-range: 5
yearmarked-donnerstag-no-lightning-zones: 
  - (-10,10)(10,-10)
yearmarked-donnerstag-no-fire-lightning: true
yearmarked-donnerstag-no-fire-lightning-damage-hearts: 3
yearmarked-donnerstag-strike-highest-blocks: true

#FISHFRYTAG
yearmarked-fishfryday: Fishfryday
yearmarked-fishfryday-bonus-xp-multiplier: 2
yearmarked-fishfryday-percent-chance-diamond: 1
yearmarked-fishfryday-percent-chance-emerald: 10
yearmarked-fishfryday-percent-chance-grass: 15
yearmarked-fishfryday-percent-chance-thordfish: 10
yearmarked-fishfryday-op-luck: true


#DIAMONDAY
yearmarked-diamonday: Diamonday
yearmarked-diamonday-bonus-diamonds: true
yearmarked-diamonday-bonus-diamonds-range-high: 3
yearmarked-diamonday-bonus-diamonds-range-low: 1

#FEATHERSDAY
yearmarked-feathersday: Feathersday
yearmarked-feathersday-prevent-fall-damage: true
yearmarked-feathersday-bounce: true
yearmarked-feathersday-bounce-xz-multiplier: 2.5




############## RECIPES ############

recipes-worlds: 
  - world

recipes: 
  - thord-fish
  - diamond-day-sword
  - fish-sword
  - fish-arrow
  - earth-day-pot-pie
  - lightning-inhibitor
  
#German/Deutsch = Thorfisch
recipe.thord-fish.name: Thordfish

recipe.thord-fish.rows: 
  - FAF
  - AAA
  - FAF
  
recipe.thord-fish.mats: 
  - F=RAW_FISH
  - A=AIR
  
recipe.thord-fish.output: RAW_FISH

recipe.thord-fish.op.only: false


#FISH NEEDLE
#German/Deutsch = Nadel
recipe.fish-sword.name: Needle

recipe.fish-sword.rows: 
  - AFA
  - AFA
  - ASA
  
recipe.fish-sword.mats: 
  - F=RAW_FISH
  - A=AIR
  - S=STICK
  
recipe.fish-sword.output: STONE_SWORD

recipe.fish-sword.item.starts.with:
  - 4=Thordfish


#DIAMOND NEEDLE
#German/Deutsch = Diamantnadel
recipe.diamond-day-sword.name: Needle

recipe.diamond-day-sword.rows: 
  - ADA
  - ADA
  - ANA
  
recipe.diamond-day-sword.mats: 
  - D=DIAMOND
  - N=STONE_SWORD
  - A=AIR
  
recipe.diamond-day-sword.output: DIAMOND_SWORD

recipe.diamond-day-sword.item.starts.with:
  - 1=Diamonday DIAMOND
  - 4=Diamonday DIAMOND
  - 7=Needle
  
#FISH ARROW
#German/Deutsch = Gr√§tenpfeil
recipe.fish-arrow.name: Fishbone Arrow

recipe.fish-arrow.rows: 
  - AAA
  - AFA
  - ASA
  
recipe.fish-arrow.mats: 
  - F=RAW_FISH
  - A=AIR
  - S=STICK
recipe.fish-arrow.output: ARROW
recipe.fish-arrow.amount: 16
recipe.fish-arrow.item.starts.with: 
  - 4=Thordfish
  

#EARTHDAY POT PIE
#German/Deutsch = Erdtag Topf Torte
recipe.earth-day-pot-pie.name: Earthday Pot Pie

recipe.earth-day-pot-pie.rows: 
  - CCC
  - PPP
  - WWW
  
recipe.earth-day-pot-pie.mats: 
  - C=CARROT_ITEM
  - P=POTATO_ITEM
  - W=WHEAT
recipe.earth-day-pot-pie.output: PUMPKIN_PIE
recipe.earth-day-pot-pie.amount: 1
recipe.earth-day-pot-pie.item.starts.with: 
  - 0={{yearmarked-earthday}}
  - 1={{yearmarked-earthday}}
  - 2={{yearmarked-earthday}}
  - 3={{yearmarked-earthday}}
  - 4={{yearmarked-earthday}}
  - 5={{yearmarked-earthday}}
  - 6={{yearmarked-earthday}}
  - 7={{yearmarked-earthday}}
  - 8={{yearmarked-earthday}}


#LIGHTNING INHIBITOR
#German/Deutsch = Blitz Hemmer
recipe.lightning-inhibitor.name: Lightning Inhibitor
recipe.lightning-inhibitor.rows: 
  - DDD
  - ASA
  - DDD
  
recipe.lightning-inhibitor.mats: 
  - D=DIAMOND
  - A=AIR
  - S=STONE_SWORD
recipe.lightning-inhibitor.output: FISHING_ROD
recipe.lightning-inhibitor.amount: 1
recipe.lightning-inhibitor.item.starts.with: 
  - 4={{recipe.fish-sword.name}}
recipe.lightning-inhibitor.keep: 
  - NNN
  - NYN
  - NNN
  
